repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.287
    hooks:
      - id: ruff
  - repo: https://github.com/ambv/black
    rev: 23.9.0
    hooks:
      - id: black
        language_version: python3.9
